// Generated by view binder compiler. Do not edit!
package com.example.zico.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.ProgressBar;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.zico.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityLoginBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  /**
   * This binding is not available in all configurations.
   * <p>
   * Present:
   * <ul>
   *   <li>layout/</li>
   * </ul>
   *
   * Absent:
   * <ul>
   *   <li>layout-w1240dp/</li>
   *   <li>layout-w936dp/</li>
   * </ul>
   */
  @Nullable
  public final CheckBox boxRememberme;

  @NonNull
  public final ConstraintLayout container;

  /**
   * This binding is not available in all configurations.
   * <p>
   * Present:
   * <ul>
   *   <li>layout/</li>
   * </ul>
   *
   * Absent:
   * <ul>
   *   <li>layout-w1240dp/</li>
   *   <li>layout-w936dp/</li>
   * </ul>
   */
  @Nullable
  public final ImageView imageView3;

  /**
   * This binding is not available in all configurations.
   * <p>
   * Present:
   * <ul>
   *   <li>layout/</li>
   * </ul>
   *
   * Absent:
   * <ul>
   *   <li>layout-w1240dp/</li>
   *   <li>layout-w936dp/</li>
   * </ul>
   */
  @Nullable
  public final ImageView imgFb;

  /**
   * This binding is not available in all configurations.
   * <p>
   * Present:
   * <ul>
   *   <li>layout/</li>
   * </ul>
   *
   * Absent:
   * <ul>
   *   <li>layout-w1240dp/</li>
   *   <li>layout-w936dp/</li>
   * </ul>
   */
  @Nullable
  public final ImageView imgGoogle;

  /**
   * This binding is not available in all configurations.
   * <p>
   * Present:
   * <ul>
   *   <li>layout/</li>
   * </ul>
   *
   * Absent:
   * <ul>
   *   <li>layout-w1240dp/</li>
   *   <li>layout-w936dp/</li>
   * </ul>
   */
  @Nullable
  public final ImageView imgTwitter;

  @NonNull
  public final ProgressBar loading;

  @NonNull
  public final Button login;

  @NonNull
  public final EditText password;

  /**
   * This binding is not available in all configurations.
   * <p>
   * Present:
   * <ul>
   *   <li>layout/</li>
   * </ul>
   *
   * Absent:
   * <ul>
   *   <li>layout-w1240dp/</li>
   *   <li>layout-w936dp/</li>
   * </ul>
   */
  @Nullable
  public final TextView txtDontacc;

  /**
   * This binding is not available in all configurations.
   * <p>
   * Present:
   * <ul>
   *   <li>layout/</li>
   * </ul>
   *
   * Absent:
   * <ul>
   *   <li>layout-w1240dp/</li>
   *   <li>layout-w936dp/</li>
   * </ul>
   */
  @Nullable
  public final TextView txtForgotpass;

  /**
   * This binding is not available in all configurations.
   * <p>
   * Present:
   * <ul>
   *   <li>layout/</li>
   * </ul>
   *
   * Absent:
   * <ul>
   *   <li>layout-w1240dp/</li>
   *   <li>layout-w936dp/</li>
   * </ul>
   */
  @Nullable
  public final TextView txtOr;

  /**
   * This binding is not available in all configurations.
   * <p>
   * Present:
   * <ul>
   *   <li>layout/</li>
   * </ul>
   *
   * Absent:
   * <ul>
   *   <li>layout-w1240dp/</li>
   *   <li>layout-w936dp/</li>
   * </ul>
   */
  @Nullable
  public final TextView txtSignin;

  /**
   * This binding is not available in all configurations.
   * <p>
   * Present:
   * <ul>
   *   <li>layout/</li>
   * </ul>
   *
   * Absent:
   * <ul>
   *   <li>layout-w1240dp/</li>
   *   <li>layout-w936dp/</li>
   * </ul>
   */
  @Nullable
  public final TextView txtSignup;

  @NonNull
  public final EditText username;

  private ActivityLoginBinding(@NonNull ConstraintLayout rootView, @Nullable CheckBox boxRememberme,
      @NonNull ConstraintLayout container, @Nullable ImageView imageView3,
      @Nullable ImageView imgFb, @Nullable ImageView imgGoogle, @Nullable ImageView imgTwitter,
      @NonNull ProgressBar loading, @NonNull Button login, @NonNull EditText password,
      @Nullable TextView txtDontacc, @Nullable TextView txtForgotpass, @Nullable TextView txtOr,
      @Nullable TextView txtSignin, @Nullable TextView txtSignup, @NonNull EditText username) {
    this.rootView = rootView;
    this.boxRememberme = boxRememberme;
    this.container = container;
    this.imageView3 = imageView3;
    this.imgFb = imgFb;
    this.imgGoogle = imgGoogle;
    this.imgTwitter = imgTwitter;
    this.loading = loading;
    this.login = login;
    this.password = password;
    this.txtDontacc = txtDontacc;
    this.txtForgotpass = txtForgotpass;
    this.txtOr = txtOr;
    this.txtSignin = txtSignin;
    this.txtSignup = txtSignup;
    this.username = username;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityLoginBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityLoginBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_login, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityLoginBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.box_Rememberme;
      CheckBox boxRememberme = ViewBindings.findChildViewById(rootView, id);

      ConstraintLayout container = (ConstraintLayout) rootView;

      id = R.id.imageView3;
      ImageView imageView3 = ViewBindings.findChildViewById(rootView, id);

      id = R.id.img_fb;
      ImageView imgFb = ViewBindings.findChildViewById(rootView, id);

      id = R.id.img_google;
      ImageView imgGoogle = ViewBindings.findChildViewById(rootView, id);

      id = R.id.img_twitter;
      ImageView imgTwitter = ViewBindings.findChildViewById(rootView, id);

      id = R.id.loading;
      ProgressBar loading = ViewBindings.findChildViewById(rootView, id);
      if (loading == null) {
        break missingId;
      }

      id = R.id.login;
      Button login = ViewBindings.findChildViewById(rootView, id);
      if (login == null) {
        break missingId;
      }

      id = R.id.password;
      EditText password = ViewBindings.findChildViewById(rootView, id);
      if (password == null) {
        break missingId;
      }

      id = R.id.txt_dontacc;
      TextView txtDontacc = ViewBindings.findChildViewById(rootView, id);

      id = R.id.txt_Forgotpass;
      TextView txtForgotpass = ViewBindings.findChildViewById(rootView, id);

      id = R.id.txt_or;
      TextView txtOr = ViewBindings.findChildViewById(rootView, id);

      id = R.id.txt_Signin;
      TextView txtSignin = ViewBindings.findChildViewById(rootView, id);

      id = R.id.txt_Signup;
      TextView txtSignup = ViewBindings.findChildViewById(rootView, id);

      id = R.id.username;
      EditText username = ViewBindings.findChildViewById(rootView, id);
      if (username == null) {
        break missingId;
      }

      return new ActivityLoginBinding((ConstraintLayout) rootView, boxRememberme, container,
          imageView3, imgFb, imgGoogle, imgTwitter, loading, login, password, txtDontacc,
          txtForgotpass, txtOr, txtSignin, txtSignup, username);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
